### ISSUE TITLE
leakage removal pretrain model?

### ISSUE THREAD

**Issue by zuowanbushiwo** [wimmerb/singing-quality-enhancement#1]
Hi @wimmerb 
     thanks for your open source work，it's  awesome  and very helpful to me .
     After carefully reading your master paper, README, and browsing the directory structure of your source, I found that there is no leakage_removal pretrain model, is that so?   `Experiments/Denoising/FullSubNet/denoise_FSN/checkpoints/best_model.tar`  is just for  Denoising ？no aec(leakage removal)  feature?
Also have the following questions：
     1. Are two models required in the actual system? one is  denoise, another  is  leakage removal?
     2. How to make it lightweight, less parameters, less GFLOS？
     3. Did you do inference on  android ? Can FullSubNet  model meet real-time performance?
     
thanks！ Looking forward to your reply
All the best

**Comment by wimmerb** [comment]
Hi @zuowanbushiwo,

you are correct that there is no pretrained leakage removal model available. The model that was trained during my thesis work was trained on some proprietary data and hence I cannot share this model.

About your other questions:
1. For leakage removal, you only need the leakage removal model. But you could try and apply a chain of denoising and then leakage removal for sure.
2. You can use adaptations of the original FullSubNet model as an orientation and play with the size of the hidden layers.
3. I didn't do inference on Android, but I reached 2.4 times real-time performance with a Macbook A1502 (Intel Core i5-5257U, 2.7 GHz).

Also, kindly take a look at chapter 7.4 (Reproducibility) of the thesis.

All the best!

**Comment by zuowanbushiwo** [comment]
Thanks!
